spring:
  application:
    name: "Facade Service"

server:
  port: 9081

articles-service:
  base-url: "https://localhost:9082"
  articles-url: "${articles-service.base-url}/api/v1/articles"

trust:
  store:
    location: "classpath:keystore/andd3dfx.p12"
    password: "andreika"
